import numpy as np
import opticalElement as opel



##Calculates upper and lower frequencies. 
## This data should actually be read from a channel.txt file
GHz = 1.e9
ch_freqs = np.array([27.0,39.0,93.0,145.0,233.0,225.0,278.0])*GHz
ch_fbw = np.array([.222,.462,.376,.276,.322,.267,.162])
ch_num = 2;

freq1 = ch_freqs[ch_num] - (ch_freqs[ch_num]*ch_fbw[ch_num])/2
freq2 = ch_freqs[ch_num] + (ch_freqs[ch_num]*ch_fbw[ch_num])/2



d = np.loadtxt("opticalChain.txt", dtype = np.str)

#Initializes each optical element
elems = []
for i in range(1, len(d)-1):
	elems.append(opel.OpticalElement(d[i], freq1,freq2))



incPowers = []

for i in range(len(elems)):
	if i==0:
		## Should append cmb power
		incPowers.append(0)
	else:
		# The power incident on element i is 
		# power on element i-1 * efficiency of element i-1 + power generated by i-1
		incPowers.append(incPowers[-1]*elems[i].eff + elems[i].power)

print "freq: %.2f GHz"%(ch_freqs[ch_num]/GHz)
print "Name\t\t\tOutput power(W)\t\tIn power(W)"
print "-"*30
for i in range(len(elems)):
	print "%8s\t\t%e\t\t%e"%(elems[i].name, elems[i].power,incPowers[i])









